### ISSUE TITLE
If I modify the command, AI can't output the code.

### ISSUE THREAD

**Issue by snailg** [ekondur/AI-Studio#10]
![image](https://github.com/ekondur/AI-Studio/assets/5671609/b4d58f50-6037-4d69-8010-52ee99a1abfb)
![image](https://github.com/ekondur/AI-Studio/assets/5671609/31896941-dfe2-408f-9710-89afee9d583a)

Using the "Add Summary" command, AI Instead of outputting code, a paragraph of text is output.
`        根据此网址 https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/recommended-tags，重构代码并添加摘要。只编写代码，不编写说明。
`

pls help,thanks!

**Comment by gluks** [comment]
I tried and it works as expected.

@snailg
Have you selected the whole method before executing the command?

**Comment by gluks** [comment]
What do you expect? You provide no information to the GPT except the name of the property. How can it guess what it is used for?
`Summary` command works with methods or with fully specified getters and setters

**Comment by ekondur** [comment]
Hi @snailg 
Could you pls write this command in your language and try again?

**Comment by snailg** [comment]
> What do you expect? You provide no information to the GPT except the name of the property. How can it guess what it is used for? `Summary` command works with methods or with fully specified getters and setters

I want to ask, this prompt should not be displayed, right?
![image](https://github.com/ekondur/AI-Studio/assets/5671609/c0aaf48a-9ac3-4da6-92f0-38e3c9cc3fd2)

**Comment by snailg** [comment]
> Hi @snailg Could you pls write this command in your language and try again?

I want to ask, this prompt should not be displayed, right?
![c59f4f18bc1525127ae0d7a2c24a5074_241825566-c0aaf48a-9ac3-4da6-92f0-38e3c9cc3fd2](https://github.com/ekondur/AI-Studio/assets/5671609/02d32b6e-7f52-46cb-8e17-3952f5cc5e6f)

**Comment by ekondur** [comment]
Hi @snailg again,
I've tested again and it seems no problem, as AI improves over time, the results can become more consistent, you can try it too, goodbye
