### ISSUE TITLE
Add setting for API endpoint

### ISSUE THREAD

**Issue by daniol** [ekondur/AI-Studio#13]
It would be helpful to be able to customize the API endpoint (default: https://api.openai.com/v1), in case someone wants to use a custom API based on OpenAI.

Since this extension is using the OpenAI package, it would need to change the value of `OpenAIAPI.ApiUrlFormat`, see https://github.com/OkGoDoIt/OpenAI-API-dotnet/blob/8e80c75afc33de0124b8e1028c33f1f494b5a73b/OpenAI_API/OpenAIAPI.cs#L23

**Comment by ekondur** [comment]
Hi @daniol 
It was released with [v1.4.0](https://github.com/ekondur/AI-Studio/releases/tag/v1.4.0), thanks for your contribution.

**Comment by LeviateK** [comment]
Fantastic! - this works against Azure OpenAI as well using the following:

https://YOUR-RESOURCE-NAME.openai.azure.com/openai/deployments/YOUR-DEPLOYMENT-NAME/{1}?api-version=2024-06-01
